#!/bin/sh
#
# An example hook script to automatically regenerate a static
# version of the Roadmap on every commit. 
#
# Called by "git commit" with no arguments.  The hook should
# exit with non-zero status after issuing an appropriate message if
# it wants to stop the commit.
#
# To use this hook, put it in your .git/hooks directory with the
# name "pre-commit"

bug roadmap > $(bug pwd)/../Roadmap.md
git add $(bug pwd)/../Roadmap.md
